
////
This file is generated! See _meta/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported fields

[partintro]

--
This document describes the fields that are exported by Filebeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-cloud>>
* <<exported-fields-docker-processor>>
* <<exported-fields-kubernetes-processor>>
* <<exported-fields-log>>
* <<exported-fields-nginx>>
* <<exported-fields-redis>>

--
[[exported-fields-beat]]
== Beat fields

Contains common beat fields available in all event types.



[float]
=== `beat.name`

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== `beat.hostname`

The hostname as returned by the operating system on which the Beat is running.


[float]
=== `beat.timezone`

The timezone as returned by the operating system on which the Beat is running.


[float]
=== `beat.version`

The version of the beat that generated this event.


[float]
=== `@timestamp`

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== `tags`

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== `fields`

type: object

Contains user configurable fields.


[float]
== error fields

Error fields containing additional info in case of errors.



[float]
=== `error.message`

type: text

Error message.


[float]
=== `error.code`

type: long

Error code.


[float]
=== `error.type`

type: keyword

Error type.


[[exported-fields-cloud]]
== Cloud provider metadata fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== `meta.cloud.provider`

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== `meta.cloud.instance_id`

Instance ID of the host machine.


[float]
=== `meta.cloud.instance_name`

Instance name of the host machine.


[float]
=== `meta.cloud.machine_type`

example: t2.medium

Machine type of the host machine.


[float]
=== `meta.cloud.availability_zone`

example: us-east-1c

Availability zone in which this host is running.


[float]
=== `meta.cloud.project_id`

example: project-x

Name of the project in Google Cloud.


[float]
=== `meta.cloud.region`

Region in which this host is running.


[[exported-fields-docker-processor]]
== Docker fields

Docker stats collected from Docker.




[float]
=== `docker.container.id`

type: keyword

Unique container id.


[float]
=== `docker.container.image`

type: keyword

Name of the image the container was built on.


[float]
=== `docker.container.name`

type: keyword

Container name.


[float]
=== `docker.container.labels`

type: object

Image labels.


[[exported-fields-kubernetes-processor]]
== Kubernetes fields

Kubernetes metadata added by the kubernetes processor




[float]
=== `kubernetes.pod.name`

type: keyword

Kubernetes pod name


[float]
=== `kubernetes.namespace`

type: keyword

Kubernetes namespace


[float]
=== `kubernetes.node.name`

type: keyword

Kubernetes node name


[float]
=== `kubernetes.labels`

type: object

Kubernetes labels map


[float]
=== `kubernetes.annotations`

type: object

Kubernetes annotations map


[float]
=== `kubernetes.container.name`

type: keyword

Kubernetes container name


[float]
=== `kubernetes.container.image`

type: keyword

Kubernetes container image


[[exported-fields-log]]
== Log file content fields

Contains log file lines.



[float]
=== `source`

type: keyword

required: True

The file from which the line was read. This field contains the absolute path to the file. For example: `/var/log/system.log`.


[float]
=== `offset`

type: long

required: False

The file offset the reported line starts at.


[float]
=== `message`

type: text

required: True

The content of the line read from the log file.


[float]
=== `stream`

type: keyword

required: False

Log stream when reading container logs, can be 'stdout' or 'stderr'


[float]
=== `prospector.type`

required: True

The prospector type from which the event was generated. This field is set to the value specified for the `type` option in the prospector section of the Filebeat config file.


[float]
=== `read_timestamp`

In case the ingest pipeline parses the timestamp from the log contents, it stores the original `@timestamp` (representing the time when the log line was read) in this field.


[float]
=== `fileset.module`

The Filebeat module that generated this event.


[float]
=== `fileset.name`

The Filebeat fileset that generated this event.


[[exported-fields-nginx]]
== Nginx fields

Module for parsing the Nginx log files.



[float]
== nginx fields

Fields from the Nginx log files.



[float]
== access fields

Contains fields for the Nginx access logs.



[float]
=== `nginx.access.remote_ip_list`

type: array

An array of remote IP addresses. It is a list because it is common to include, besides the client IP address, IP addresses from headers like `X-Forwarded-For`. See also the `remote_ip` field.


[float]
=== `nginx.access.remote_ip`

type: keyword

Client IP address. The first public IP address from the `remote_ip_list` array. If no public IP addresses are present, this field contains the first private IP address from the `remote_ip_list` array.


[float]
=== `nginx.access.user_name`

type: keyword

The user name used when basic authentication is used.


[float]
=== `nginx.access.method`

type: keyword

example: GET

The request HTTP method.


[float]
=== `nginx.access.url`

type: keyword

The request HTTP URL.


[float]
=== `nginx.access.http_version`

type: keyword

The HTTP version.


[float]
=== `nginx.access.response_code`

type: long

The HTTP response code.


[float]
=== `nginx.access.body_sent.bytes`

type: long

format: bytes

The number of bytes of the server response body.


[float]
=== `nginx.access.referrer`

type: keyword

The HTTP referrer.


[float]
=== `nginx.access.agent`

type: text

Contains the un-parsed user agent string. Only present if the user agent Elasticsearch plugin is not available or not used.


[float]
== user_agent fields

Contains the parsed User agent field. Only present if the user agent Elasticsearch plugin is available and used.



[float]
=== `nginx.access.user_agent.device`

type: keyword

The name of the physical device.


[float]
=== `nginx.access.user_agent.major`

type: long

The major version of the user agent.


[float]
=== `nginx.access.user_agent.minor`

type: long

The minor version of the user agent.


[float]
=== `nginx.access.user_agent.patch`

type: keyword

The patch version of the user agent.


[float]
=== `nginx.access.user_agent.name`

type: keyword

example: Chrome

The name of the user agent.


[float]
=== `nginx.access.user_agent.os`

type: keyword

The name of the operating system.


[float]
=== `nginx.access.user_agent.os_major`

type: long

The major version of the operating system.


[float]
=== `nginx.access.user_agent.os_minor`

type: long

The minor version of the operating system.


[float]
=== `nginx.access.user_agent.os_name`

type: keyword

The name of the operating system.


[float]
== geoip fields

Contains GeoIP information gathered based on the remote_ip field. Only present if the GeoIP Elasticsearch plugin is available and used.



[float]
=== `nginx.access.geoip.continent_name`

type: keyword

The name of the continent.


[float]
=== `nginx.access.geoip.country_iso_code`

type: keyword

Country ISO code.


[float]
=== `nginx.access.geoip.location`

type: geo_point

The longitude and latitude.


[float]
=== `nginx.access.geoip.region_name`

type: keyword

The region name.


[float]
=== `nginx.access.geoip.city_name`

type: keyword

The city name.


[float]
== error fields

Contains fields for the Nginx error logs.



[float]
=== `nginx.error.level`

type: keyword

Error level (e.g. error, critical).


[float]
=== `nginx.error.pid`

type: long

Process identifier (PID).


[float]
=== `nginx.error.tid`

type: long

Thread identifier.


[float]
=== `nginx.error.connection_id`

type: long

Connection identifier.


[float]
=== `nginx.error.message`

type: text

The error message


[[exported-fields-redis]]
== Redis fields

Redis Module



[float]
== redis fields




[float]
== log fields

Redis log files



[float]
=== `redis.log.pid`

type: long

The process ID of the Redis server.


[float]
=== `redis.log.role`

type: keyword

The role of the Redis instance. Can be one of `master`, `slave`, `child` (for RDF/AOF writing child), or `sentinel`.


[float]
=== `redis.log.level`

type: keyword

The log level. Can be one of `debug`, `verbose`, `notice`, or `warning`.


[float]
=== `redis.log.message`

type: text

The log message


[float]
== slowlog fields

Slow logs are retrieved from Redis via a network connection.



[float]
=== `redis.slowlog.cmd`

type: keyword

The command executed.


[float]
=== `redis.slowlog.duration.us`

type: long

How long it took to execute the command in microseconds.


[float]
=== `redis.slowlog.id`

type: long

The ID of the query.


[float]
=== `redis.slowlog.key`

type: keyword

The key on which the command was executed.


[float]
=== `redis.slowlog.args`

type: keyword

The arguments with which the command was called.


